SELECT
    t1.REPORTREF,
    t2.ASSET,
    t3.INSTCLASS,
    t1.NETAMT,
    t2.CLICSD,
    t2.INTRST
FROM
    GLDATA/TXNREPESMA t1
JOIN GLDATA/CONTCT t2 ON t2.FRMCOD || t2.YEAR || t2.ACCLTR || t2.CONTNO || '1' = t1.REPORTREF
LEFT JOIN GLDATA/SECFIG t3 ON t3.SEDOL = t2.ASSET
WHERE
    t1.REPORTREF IN (
    -- TRANSACTION REFERENCES --
    )