WITH LinkCodes AS (
  SELECT 
    t4.CLINUM, 
    MAX(
      CASE WHEN t4.RLNKTP = 'BEN' THEN t4.ROTCOD END
    ) AS BEN_LINK, 
    MAX(
      CASE WHEN t4.RLNKTP = 'OWN' THEN t4.ROTCOD END
    ) AS OWN_LINK
  FROM 
    GLDATA / ROTCLI t4 
  GROUP BY 
    t4.CLINUM
c)

  SELECT 
    t1.REPORTREF, 
    t2.CLINUM, 
    lc.BEN_LINK, 
    lc.OWN_LINK, 
    t5.UECODE, 
    t6b.UETYPE,
    CASE WHEN t5.INDIDCODE <> '' THEN t5.INDIDCODE ELSE t6.UENINO END AS SELLER_ID_CODE, 
    CASE WHEN t5.INDIDCODE = '' 
    OR t5.INDIDCODE IS NULL THEN 'NINO' ELSE t5.PTYSCHCODE END AS SELLER_ID_TYPE, 
    t5.PTYFORE, 
    t5.PTYSURN, 
    CASE WHEN t5.PTYDOB IS NULL 
    OR t5.PTYDOB <= DATE('1941-01-01') THEN NULL ELSE t5.PTYDOB END AS PTYDOB, 
    CASE 
    WHEN UPPER(
      SUBSTR(
        t3.CLNAME, 
        1, 
        LOCATE(' ', t3.CLNAME) -1
      )
    ) IN ('MR', 'MASTER') THEN 'M' WHEN UPPER(
      SUBSTR(
        t3.CLNAME, 
        1, 
        LOCATE(' ', t3.CLNAME) -1
      )
    ) IN ('MRS', 'MISS', 'MS') THEN 'F' WHEN UPPER(
      SUBSTR(
        t3.CLNAME, 
        1, 
        LOCATE(' ', t3.CLNAME) -1
      )
    ) IN ('DR', 'PROF') THEN 'N/A' ELSE 'N/A' END AS CLIENT_GENDER, 
    t6.UENAT, 
    t7.NATION, 
    t1.TRDDATTIM
  FROM 
    GLDATA / TXNREPESMA t1 
    JOIN GLDATA / CONTCT t2 ON t2.FRMCOD || t2.YEAR || t2.ACCLTR || t2.CONTNO || '1' = t1.REPORTREF 
    AND BUYSEL = 'S'
    JOIN GLDATA / CLIENT t3 ON t2.CLINUM = t3.CLINO 
    JOIN GLDATA / ESMAPTYIND t5 ON t1.REPORTREF = t5.REPORTREF
    LEFT JOIN GLDATA / PERSON t6 ON t5.UECODE = t6.UECODE 
    LEFT JOIN GLDATA / PERSON t6b	ON SUBSTR(t2.CLINUM, 1, LENGTH(t2.CLINUM) - 1) = t6b.UECODE
    LEFT JOIN GLDATA / PERSONNAT t7 ON t3.UECODE = t7.UECODE 
    LEFT JOIN GLDATA / ESMAPTYIND t5b ON t1.SELDECIND = t5b.PTYSCHCODE 
    LEFT JOIN LinkCodes lc ON t2.CLINUM = lc.CLINUM 
  WHERE 
    t1.REPORTREF IN (
      -- TRANSACTION REFERENCES --
      )
