SELECT
    t1.REPORTREF,
    t2.CLINO,
    CASE
        WHEN t3.INDIDCODE <> '' THEN t3.INDIDCODE
        ELSE t4.ENTIDCODE
    END AS Buyer_ID_Code,
    CASE
        WHEN t1.BUYDECIND <> '' THEN t1.BUYDECIND
        ELSE t1.BUYDECENT
    END AS Buyer_DM_Code,
    t2.CLNTTY,
    t2.TSATYP,
    CASE
		WHEN t2.BRNCH3 <> ''
		THEN t2.BRNCH3
		ELSE t2.PARTNR
	END AS BGETTER
FROM
    GLDATA/TXNREPESMA t1
    JOIN GLDATA/CONTCT t7 ON 
        t7.FRMCOD
        || t7.YEAR
        || t7.ACCLTR
        || t7.CONTNO
        || '1' = t1.REPORTREF 
    JOIN GLDATA/CLIENT t2 ON t7.CLINUM = t2.CLINO
    LEFT JOIN GLDATA/ESMAPTYIND t3 ON t1.REPORTREF = t3.REPORTREF
		AND t3.PARTY = 'BUYER'
    LEFT JOIN GLDATA/ESMAPTYENT t4 ON t1.REPORTREF = t4.REPORTREF
		AND t4.PARTY = 'BUYER'
WHERE
    t1.REPORTREF IN (
        -- TRANSACTION REFERENCES --
	)
LIMIT 50000