"""MiFIR RTS 22 rule catalogue.

Static catalogue of MiFIR Article 26 / RTS 22 (Commission Delegated Regulation
(EU) 2017/590) reporting rules, extracted from the ISDA DRR model file
``regulation-esma-mifir-rule.rosetta`` (distribution 6.34.1).

Every entry corresponds to a ``reporting rule`` or ``eligibility rule`` in the
DRR Rosetta DSL.  All rules are currently ``extract "Not Modelled"`` stubs in
DRR 6.34.1; the catalogue captures the regulatory references so that
txr_automation validation output carries DRR-compatible traceability now, with
rule logic to be supplied by a future DRR release.

Structure of each rule entry:
    rule_name       – Rosetta DSL rule identifier
    field_number    – RTS 22 Annex I Table 2 field number
    field_name      – Descriptive name from the annex
    regulation      – Source regulation reference
    provision       – Exact text from Commission Delegated Regulation (EU) 2017/590
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class RuleReference:
    """A single DRR regulatory rule reference."""

    rule_name: str
    field_number: str
    field_name: str
    regulation: str
    provision: str


# ---------------------------------------------------------------------------
# Full RTS 22 Annex I Table 2 catalogue
# ---------------------------------------------------------------------------

CATALOGUE: dict[str, RuleReference] = {
    r.rule_name: r
    for r in [
        RuleReference(
            rule_name="ReportStatus",
            field_number="1",
            field_name="Report status",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 1",
            provision="Indication as to whether the transaction report is new or a cancellation.",
        ),
        RuleReference(
            rule_name="TransactionReferenceNumber",
            field_number="2",
            field_name="Transaction reference number",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 2",
            provision=(
                "Identification number that is unique to the executing firm for each "
                "transaction report."
            ),
        ),
        RuleReference(
            rule_name="TradingVenueTransactionIdentificationCode",
            field_number="3",
            field_name="Trading venue transaction identification code",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 3",
            provision=(
                "This is a number generated by trading venues and disseminated to both the "
                "buying and the selling parties in accordance with Article 12 of Commission "
                "Delegated Regulation (EU) 2017/580."
            ),
        ),
        RuleReference(
            rule_name="ExecutingEntityIdentificationCode",
            field_number="4",
            field_name="Executing entity identification code",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 4",
            provision="Code used to identify the entity executing the transaction.",
        ),
        RuleReference(
            rule_name="IsInvestmentFirm",
            field_number="5",
            field_name="Investment firm indicator",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 5",
            provision=(
                "Indicates whether the entity identified in field 4 is an investment firm "
                "covered by Article 4(1) of Directive 2014/65/EU."
            ),
        ),
        RuleReference(
            rule_name="BuyerSeller_Buyer",
            field_number="7",
            field_name="Buyer identification code",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 7",
            provision=(
                "Code used to identify the acquirer of the financial instrument. "
                "Where the acquirer is a legal entity, the LEI code of the acquirer shall be used. "
                "Where the acquirer is a non-legal entity, the identifier specified in Article 6 "
                "shall be used."
            ),
        ),
        RuleReference(
            rule_name="BuyerSeller_Seller",
            field_number="16",
            field_name="Seller identification code",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 16",
            provision=(
                "Code used to identify the disposer of the financial instrument. "
                "Where the disposer is a legal entity, the LEI code of the disposer shall be used. "
                "Where the disposer is a non-legal entity, the identifier specified in Article 6 "
                "shall be used."
            ),
        ),
        RuleReference(
            rule_name="TransmissionOfOrderIndicator",
            field_number="25",
            field_name="Transmission of order indicator",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 25",
            provision=(
                "'true' shall be populated by the transmitting firm within the transmitting "
                "firm's report where the conditions for transmission specified in Article 4 "
                "were not satisfied. 'false' in all other circumstances."
            ),
        ),
        RuleReference(
            rule_name="TradingDateTime",
            field_number="28",
            field_name="Trading date time",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 28",
            provision=(
                "Date and time when the transaction was executed. For transactions executed "
                "on a trading venue, the level of granularity shall be in accordance with the "
                "requirements set out in Article of Commission Delegated Regulation (EU) 2017/574. "
                "For transactions not executed on a trading venue the time reported shall be at "
                "least to the nearest second."
            ),
        ),
        RuleReference(
            rule_name="TradingCapacity",
            field_number="29",
            field_name="Trading capacity",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 29",
            provision=(
                "Indication of whether the transaction results from the executing firm carrying "
                "out matched principal trading under Article 4(1)(38) of Directive 2014/65/EU or "
                "dealing on own account under Article 4(1)(6) of Directive 2014/65/EU."
            ),
        ),
        RuleReference(
            rule_name="Quantity",
            field_number="30",
            field_name="Quantity",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 30",
            provision=(
                "The number of units of the financial instrument, or the number of derivative "
                "contracts in the transaction. The nominal or monetary value of the financial "
                "instrument."
            ),
        ),
        RuleReference(
            rule_name="Price",
            field_number="33",
            field_name="Price",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 33",
            provision=(
                "The information reported in this field shall be consistent with the values "
                "provided in fields 30 and 46."
            ),
        ),
        RuleReference(
            rule_name="VenueOfExecution",
            field_number="36",
            field_name="Venue of execution",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 36",
            provision=(
                "Identification of the venue where the transaction was executed. Use the ISO 10383 "
                "segment MIC for transactions executed on a trading venue, Systematic Internaliser "
                "(SI) or organised trading platform outside of the Union."
            ),
        ),
        RuleReference(
            rule_name="InstrumentIdentificationCode",
            field_number="41",
            field_name="Instrument identification code",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 41",
            provision=(
                "Code used to identify the financial instrument. This field applies to financial "
                "instruments for which a request for admission to trading has been made, that are "
                "admitted to trading or traded on a trading venue or on a systematic internaliser."
            ),
        ),
        RuleReference(
            rule_name="InstrumentFullName",
            field_number="42",
            field_name="Instrument full name",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 42",
            provision="Full name of the financial instrument.",
        ),
        RuleReference(
            rule_name="InstrumentClassification",
            field_number="43",
            field_name="Instrument classification",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 43",
            provision=(
                "Taxonomy used to classify the financial instrument. A complete and accurate "
                "CFI code shall be provided."
            ),
        ),
        RuleReference(
            rule_name="NotionalCurrency1",
            field_number="44",
            field_name="Notional currency 1",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 44",
            provision=(
                "Currency in which the notional is denominated. In the case of an interest rate "
                "or currency derivative contract, this will be the notional currency of leg 1 or "
                "the currency 1 of the pair."
            ),
        ),
        RuleReference(
            rule_name="PriceMultiplier",
            field_number="46",
            field_name="Price multiplier",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 46",
            provision=(
                "Number of units of the underlying instrument represented by a single derivative "
                "contract."
            ),
        ),
        RuleReference(
            rule_name="InvestmentDecisionWithinFirm",
            field_number="57",
            field_name="Investment decision within firm",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 57",
            provision=(
                "Code used to identify the person or algorithm within the investment firm who is "
                "responsible for the investment decision. For natural persons, the identifier "
                "specified in Article 6 shall be used. If the investment decision was made by an "
                "algorithm, the field shall be populated as set out in Article 8."
            ),
        ),
        RuleReference(
            rule_name="PersonResponsibleForInvestmentDecisionCountry",
            field_number="58",
            field_name="Country of branch supervising investment decision",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 58",
            provision=(
                "Code used to identify the country of the branch of the investment firm for the "
                "person responsible for the investment decision, as set out in Article 14(3)(b)."
            ),
        ),
        RuleReference(
            rule_name="ExecutionWithinFirm",
            field_number="59",
            field_name="Execution within firm",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 59",
            provision=(
                "Code used to identify the person or algorithm within the investment firm who is "
                "responsible for the execution. For natural persons, the identifier specified in "
                "Article 6 shall be used."
            ),
        ),
        RuleReference(
            rule_name="PersonResponsibleForExecutionCountry",
            field_number="60",
            field_name="Country of branch supervising execution",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 60",
            provision=(
                "Code used to identify the country of the branch of the investment firm for the "
                "person responsible for the execution of the transaction, as set out in "
                "Article 14(3)(c)."
            ),
        ),
        RuleReference(
            rule_name="MaturityDate",
            field_number="54",
            field_name="Maturity date",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 54",
            provision=(
                "Date of maturity of the financial instrument. Field only applies to debt "
                "instruments with defined maturity."
            ),
        ),
        RuleReference(
            rule_name="SecuritiesFinancingTransactionIndicator",
            field_number="65",
            field_name="Securities financing transaction indicator",
            regulation="ESMA MiFIR RTS_22 Annex I Table 2 Field 65",
            provision=(
                "'true' shall be populated where the transaction falls within the scope of "
                "activity but is exempted from reporting under Regulation (EU) 2015/2365. "
                "'false' otherwise."
            ),
        ),
    ]
}


# ---------------------------------------------------------------------------
# Mapping: txr_automation validator name → DRR rule name(s)
# ---------------------------------------------------------------------------

VALIDATOR_TO_RULES: dict[str, list[str]] = {
    "validate-buyer": ["BuyerSeller_Buyer"],
    "validate-seller": ["BuyerSeller_Seller"],
    "validate-inconsistent-buyer": ["BuyerSeller_Buyer"],
    "validate-inconsistent-seller": ["BuyerSeller_Seller"],
    "validate-ftbdm": ["InvestmentDecisionWithinFirm"],
    "validate-ftsdm": ["InvestmentDecisionWithinFirm"],
    "validate-incorrect-net-amount": ["Quantity", "Price"],
    "validate-non-zero-net-qty": ["Quantity"],
    "validate-non-zero-net-amt": ["Quantity", "Price"],
    "validate-incorrect-time": ["TradingDateTime"],
}


def get_rules_for_validator(validator_name: str) -> list[RuleReference]:
    """Return the DRR rule references that correspond to a txr validator."""
    return [
        CATALOGUE[r]
        for r in VALIDATOR_TO_RULES.get(validator_name, [])
        if r in CATALOGUE
    ]
