#!/usr/bin/env python3
"""
File Browser Tab
================

Output repository for viewing logs and output files generated by completed
automation jobs.  Jobs are fetched from the API, grouped by module, and
displayed in a three-pane layout:

- Module list (top-left)
- Job list for selected module (bottom-left)
- Log viewer and output file previewer (right)

Output files are previewed via the API filesystem endpoint.  When a file
exists on the local filesystem, "Open Externally" and "Show in Explorer"
buttons become available.
"""

import csv
import io
import subprocess
import sys
from collections import defaultdict
from typing import Any, Dict, List, Optional

from PySide6.QtCore import Qt, QThread, QUrl, Signal
from PySide6.QtGui import QDesktopServices
from PySide6.QtWidgets import (
    QAbstractItemView,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QListWidget,
    QListWidgetItem,
    QPlainTextEdit,
    QPushButton,
    QSplitter,
    QStackedWidget,
    QTableWidget,
    QTableWidgetItem,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from gui.api.client import ApiClient

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_MODULE_LABELS: Dict[str, str] = {
    "accuracy_testing": "Accuracy Testing",
    "fca": "FCA Register",
    "firds": "FIRDS",
    "gleif": "GLEIF",
    "replay": "Replay",
    "utils": "Utilities",
    "utilities": "Utilities",
    "reconciliation": "Reconciliation",
    "automation": "Automation",
}

# Keys that may contain the configured output file path in a configSnapshot.
_OUTPUT_KEYS = ("output_file", "outputFile", "output", "replay_output", "replayOutput")

_MAX_CSV_ROWS = 1_000  # Maximum rows to show in the CSV table view

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_module_key(script_name: str) -> str:
    """Extract the module segment from a dotted script name, e.g. ``src.fca.scripts.check_firm`` → ``fca``."""
    parts = script_name.split(".")
    if len(parts) >= 2 and parts[0] == "src":
        return parts[1]
    return script_name


def _get_module_label(key: str) -> str:
    """Return a human-readable label for a module key."""
    return _MODULE_LABELS.get(key, key.replace("_", " ").title())


def _extract_output_files(snapshot: Optional[Dict[str, Any]]) -> List[str]:
    """Return a deduplicated list of output file paths from a configSnapshot dict."""
    if not snapshot:
        return []
    seen: set = set()
    result: List[str] = []
    for k in _OUTPUT_KEYS:
        val = snapshot.get(k)
        if isinstance(val, str) and val and val not in seen:
            seen.add(val)
            result.append(val)
    return result


def _basename(path: str) -> str:
    """Return the filename component of a path (handles both / and \\)."""
    return path.replace("\\", "/").split("/")[-1] or path


# ---------------------------------------------------------------------------
# Background workers
# ---------------------------------------------------------------------------


class _JobFetchWorker(QThread):
    """Fetches the jobs list from the API in a background thread."""

    jobs_ready = Signal(list)
    error = Signal(str)

    def __init__(self, client: ApiClient, parent: Optional[QWidget] = None) -> None:
        super().__init__(parent)
        self._client = client

    def run(self) -> None:
        try:
            from gui.api.jobs import list_jobs  # local import avoids circular dependency

            jobs: List[Dict[str, Any]] = list_jobs(self._client, limit=200)
            self.jobs_ready.emit(jobs)
        except Exception as exc:  # noqa: BLE001
            self.error.emit(str(exc))


class _FileContentWorker(QThread):
    """Fetches file content from the API ``/api/filesystem/read`` endpoint."""

    content_ready = Signal(str, bool, str)  # (content, truncated, filename)
    error = Signal(str)

    def __init__(
        self, client: ApiClient, path: str, parent: Optional[QWidget] = None
    ) -> None:
        super().__init__(parent)
        self._client = client
        self._path = path

    def run(self) -> None:
        try:
            result: Dict[str, Any] = self._client.get(
                "/api/filesystem/read", params={"path": self._path}
            )
            self.content_ready.emit(
                result.get("content", ""),
                bool(result.get("truncated", False)),
                result.get("name", _basename(self._path)),
            )
        except Exception as exc:  # noqa: BLE001
            self.error.emit(str(exc))


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------


def _set_mono_font(widget: QPlainTextEdit) -> None:
    """Apply a monospace font to a QPlainTextEdit."""
    font = widget.font()
    font.setFamily("Consolas, Courier New, monospace")
    font.setPointSize(9)
    widget.setFont(font)


# ---------------------------------------------------------------------------
# FileBrowserTab
# ---------------------------------------------------------------------------


class FileBrowserTab(QWidget):
    """
    Output repository tab.

    Displays completed jobs grouped by module.  Selecting a job shows its
    captured log output and any configured output files for preview or download.
    """

    def __init__(
        self,
        api_client: Optional[ApiClient] = None,
        parent: Optional[QWidget] = None,
    ) -> None:
        super().__init__(parent)
        self._client = api_client
        self._jobs: List[Dict[str, Any]] = []
        self._module_jobs: Dict[str, List[Dict[str, Any]]] = {}
        self._current_job: Optional[Dict[str, Any]] = None
        self._current_file_path: Optional[str] = None
        self._fetch_worker: Optional[_JobFetchWorker] = None
        self._file_worker: Optional[_FileContentWorker] = None

        self._build_ui()

        if self._client:
            self._refresh()

    # ------------------------------------------------------------------
    # UI construction
    # ------------------------------------------------------------------

    def _build_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(6, 6, 6, 6)
        layout.setSpacing(6)

        # Header row
        header = QHBoxLayout()
        title = QLabel("<b>Output Files</b>")
        header.addWidget(title, 1)
        self._refresh_btn = QPushButton("Refresh")
        self._refresh_btn.setFixedWidth(80)
        self._refresh_btn.clicked.connect(self._refresh)
        header.addWidget(self._refresh_btn)
        layout.addLayout(header)

        # Status label
        self._status_label = QLabel()
        self._status_label.setStyleSheet("color: grey;")
        layout.addWidget(self._status_label)

        if not self._client:
            self._status_label.setText(
                "API client not available. Cannot load job history."
            )
            self._refresh_btn.setEnabled(False)
            return

        # Main splitter
        splitter = QSplitter(Qt.Orientation.Horizontal)

        # ---- Left pane: module list + job list ----
        left = QWidget()
        left_layout = QVBoxLayout(left)
        left_layout.setContentsMargins(0, 0, 0, 0)
        left_layout.setSpacing(4)

        left_layout.addWidget(QLabel("<b>Module</b>"))
        self._module_list = QListWidget()
        self._module_list.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self._module_list.currentRowChanged.connect(self._on_module_selected)
        left_layout.addWidget(self._module_list, 1)

        left_layout.addWidget(QLabel("<b>Jobs</b>"))
        self._job_list = QListWidget()
        self._job_list.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self._job_list.currentRowChanged.connect(self._on_job_selected)
        left_layout.addWidget(self._job_list, 2)

        splitter.addWidget(left)

        # ---- Right pane: tab widget (Log | Output Files) ----
        self._tabs = QTabWidget()

        # Log tab
        self._log_viewer = QPlainTextEdit()
        self._log_viewer.setReadOnly(True)
        self._log_viewer.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        _set_mono_font(self._log_viewer)
        self._log_viewer.setPlaceholderText("Select a job to view its captured log output.")
        self._tabs.addTab(self._log_viewer, "Log")

        # Output Files tab
        files_widget = QWidget()
        files_layout = QVBoxLayout(files_widget)
        files_layout.setContentsMargins(4, 4, 4, 4)
        files_layout.setSpacing(6)

        # Action buttons row
        btn_row = QHBoxLayout()
        self._open_btn = QPushButton("Open Externally")
        self._open_btn.setEnabled(False)
        self._open_btn.setToolTip("Open this file with the default application.")
        self._open_btn.clicked.connect(self._on_open_externally)
        btn_row.addWidget(self._open_btn)
        self._explorer_btn = QPushButton("Show in Explorer")
        self._explorer_btn.setEnabled(False)
        self._explorer_btn.setToolTip("Reveal this file in Windows Explorer.")
        self._explorer_btn.clicked.connect(self._on_show_in_explorer)
        btn_row.addWidget(self._explorer_btn)
        btn_row.addStretch()
        files_layout.addLayout(btn_row)

        # File list (small, max height capped)
        self._file_list = QListWidget()
        self._file_list.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self._file_list.setMaximumHeight(110)
        self._file_list.currentRowChanged.connect(self._on_file_selected)
        files_layout.addWidget(self._file_list)

        # Content area status + stacked viewer
        self._file_status = QLabel()
        self._file_status.setStyleSheet("color: grey; font-size: small;")
        files_layout.addWidget(self._file_status)

        self._content_stack = QStackedWidget()

        # Plain-text viewer (default)
        self._text_viewer = QPlainTextEdit()
        self._text_viewer.setReadOnly(True)
        self._text_viewer.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        _set_mono_font(self._text_viewer)
        self._text_viewer.setPlaceholderText("Select an output file to preview its contents.")
        self._content_stack.addWidget(self._text_viewer)

        # CSV table viewer
        self._csv_table = QTableWidget()
        self._csv_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self._csv_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self._csv_table.horizontalHeader().setSectionResizeMode(
            QHeaderView.ResizeMode.ResizeToContents
        )
        self._content_stack.addWidget(self._csv_table)

        files_layout.addWidget(self._content_stack, 1)
        self._tabs.addTab(files_widget, "Output Files")

        splitter.addWidget(self._tabs)
        splitter.setSizes([220, 580])
        layout.addWidget(splitter, 1)

    # ------------------------------------------------------------------
    # Data loading
    # ------------------------------------------------------------------

    def _refresh(self) -> None:
        """Fetch jobs from the API."""
        if not self._client:
            return
        self._refresh_btn.setEnabled(False)
        self._status_label.setText("Loading jobs\u2026")
        if self._fetch_worker and self._fetch_worker.isRunning():
            self._fetch_worker.terminate()
            self._fetch_worker.wait(1000)
        self._fetch_worker = _JobFetchWorker(self._client, parent=self)
        self._fetch_worker.jobs_ready.connect(self._on_jobs_ready)
        self._fetch_worker.error.connect(self._on_fetch_error)
        self._fetch_worker.finished.connect(lambda: self._refresh_btn.setEnabled(True))
        self._fetch_worker.start()

    def _on_jobs_ready(self, jobs: list) -> None:
        finished = [j for j in jobs if j.get("status") in ("success", "failed")]
        groups: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
        for job in finished:
            key = _get_module_key(job.get("scriptName", ""))
            groups[key].append(job)
        for group in groups.values():
            group.sort(
                key=lambda j: j.get("completedAt") or j.get("createdAt") or "",
                reverse=True,
            )
        self._module_jobs = dict(groups)
        self._populate_module_list()
        count = len(finished)
        n_mods = len(groups)
        self._status_label.setText(
            f"{count} completed job{'s' if count != 1 else ''} across "
            f"{n_mods} module{'s' if n_mods != 1 else ''}."
        )

    def _on_fetch_error(self, message: str) -> None:
        msg_lower = message.lower()
        if "max retries" in msg_lower or "connection" in msg_lower or "refused" in msg_lower:
            url = self._client.base_url if self._client else "the API server"
            self._status_label.setText(
                f"Cannot connect to the API server ({url}). "
                "Start the API backend and click Refresh."
            )
        else:
            self._status_label.setText(f"Error loading jobs: {message}")

    # ------------------------------------------------------------------
    # Module / job selection
    # ------------------------------------------------------------------

    def _populate_module_list(self) -> None:
        self._module_list.blockSignals(True)
        self._module_list.clear()
        for key, jobs in self._module_jobs.items():
            label = _get_module_label(key)
            item = QListWidgetItem(f"{label}  ({len(jobs)})")
            item.setData(Qt.ItemDataRole.UserRole, key)
            self._module_list.addItem(item)
        self._module_list.blockSignals(False)
        if self._module_list.count() > 0:
            self._module_list.setCurrentRow(0)

    def _on_module_selected(self, row: int) -> None:
        if row < 0:
            self._job_list.clear()
            return
        item = self._module_list.item(row)
        if item is None:
            return
        key: str = item.data(Qt.ItemDataRole.UserRole)
        jobs = self._module_jobs.get(key, [])
        self._job_list.blockSignals(True)
        self._job_list.clear()
        for job in jobs:
            completed_at = job.get("completedAt") or ""
            if completed_at:
                try:
                    from datetime import datetime

                    dt = datetime.fromisoformat(completed_at.replace("Z", "+00:00"))
                    completed_at = dt.astimezone().strftime("%Y-%m-%d %H:%M")
                except ValueError:
                    pass
            script = job.get("scriptName", "")
            friendly = script.split(".")[-1].replace("_", " ").title()
            status = job.get("status", "")
            jitem = QListWidgetItem(f"{friendly}  [{status}]  {completed_at}")
            jitem.setData(Qt.ItemDataRole.UserRole, job)
            self._job_list.addItem(jitem)
        self._job_list.blockSignals(False)
        if self._job_list.count() > 0:
            self._job_list.setCurrentRow(0)

    def _on_job_selected(self, row: int) -> None:
        if row < 0:
            return
        item = self._job_list.item(row)
        if item is None:
            return
        job: Dict[str, Any] = item.data(Qt.ItemDataRole.UserRole)
        self._current_job = job
        self._show_job(job)

    def _show_job(self, job: Dict[str, Any]) -> None:
        """Populate the right pane with the selected job's log and output files."""
        log_output: str = job.get("logOutput") or "(No log output captured for this job.)"
        self._log_viewer.setPlainText(log_output)

        snapshot = job.get("configSnapshot")
        output_files = _extract_output_files(snapshot)

        self._file_list.clear()
        self._current_file_path = None
        self._open_btn.setEnabled(False)
        self._explorer_btn.setEnabled(False)
        self._text_viewer.clear()
        self._csv_table.clearContents()
        self._csv_table.setRowCount(0)
        self._file_status.setText("")

        for path in output_files:
            name = _basename(path)
            fitem = QListWidgetItem(f"\U0001f4c4 {name}")
            fitem.setData(Qt.ItemDataRole.UserRole, path)
            fitem.setToolTip(path)
            self._file_list.addItem(fitem)

        if output_files:
            self._file_list.setCurrentRow(0)

        # Switch to Log tab by default (unless no log and there are files)
        if not log_output.strip() and output_files:
            self._tabs.setCurrentIndex(1)
        else:
            self._tabs.setCurrentIndex(0)

    # ------------------------------------------------------------------
    # File selection and preview
    # ------------------------------------------------------------------

    def _on_file_selected(self, row: int) -> None:
        if row < 0:
            return
        item = self._file_list.item(row)
        if item is None:
            return
        path: str = item.data(Qt.ItemDataRole.UserRole)
        self._current_file_path = path
        import os as _os  # noqa: PLC0415

        local_exists = _os.path.isfile(path)
        self._open_btn.setEnabled(local_exists)
        self._open_btn.setToolTip(
            "Open this file with the default application."
            if local_exists
            else "File not found on local filesystem."
        )
        self._explorer_btn.setEnabled(local_exists and sys.platform == "win32")

        self._file_status.setText("Loading\u2026")
        if self._file_worker and self._file_worker.isRunning():
            self._file_worker.terminate()
            self._file_worker.wait(1000)
        if self._client:
            self._file_worker = _FileContentWorker(self._client, path, parent=self)
            self._file_worker.content_ready.connect(self._on_file_content)
            self._file_worker.error.connect(self._on_file_error)
            self._file_worker.start()
        else:
            self._file_status.setText("API client not available.")

    def _on_file_content(self, content: str, truncated: bool, name: str) -> None:
        suffix = "  [first 1\u00a0MB shown]" if truncated else ""
        self._file_status.setText(f"{name}{suffix}")
        if name.lower().endswith(".csv"):
            self._populate_csv_table(content)
            self._content_stack.setCurrentWidget(self._csv_table)
        else:
            self._text_viewer.setPlainText(content)
            self._content_stack.setCurrentWidget(self._text_viewer)

    def _on_file_error(self, message: str) -> None:
        self._file_status.setText(f"Could not load file: {message}")
        self._text_viewer.setPlainText(
            "File could not be retrieved from the API.\n"
            "It may not exist on the server, or may have been moved."
        )
        self._content_stack.setCurrentWidget(self._text_viewer)

    def _populate_csv_table(self, content: str) -> None:
        """Parse CSV content and populate the QTableWidget."""
        self._csv_table.clearContents()
        reader = csv.reader(io.StringIO(content))
        rows = list(reader)
        if not rows:
            self._csv_table.setRowCount(0)
            self._csv_table.setColumnCount(0)
            return
        headers = rows[0]
        data_rows = rows[1 : _MAX_CSV_ROWS + 1]
        self._csv_table.setColumnCount(len(headers))
        self._csv_table.setHorizontalHeaderLabels(headers)
        self._csv_table.setRowCount(len(data_rows))
        for ri, row in enumerate(data_rows):
            for ci, cell in enumerate(row):
                if ci < len(headers):
                    self._csv_table.setItem(ri, ci, QTableWidgetItem(cell))

    # ------------------------------------------------------------------
    # External actions
    # ------------------------------------------------------------------

    def _on_open_externally(self) -> None:
        """Open the currently selected file with the OS default application."""
        if self._current_file_path:
            QDesktopServices.openUrl(QUrl.fromLocalFile(self._current_file_path))

    def _on_show_in_explorer(self) -> None:
        """Reveal the currently selected file in Windows Explorer."""
        if self._current_file_path and sys.platform == "win32":
            import os as _os  # noqa: PLC0415

            norm = _os.path.normpath(self._current_file_path)
            subprocess.Popen(["explorer", "/select,", norm])
